services:
  - type: web
    name: link-sea-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://linkseadb_owner:yMY7Rht4CTKe@ep-young-snow-a567v3yt.us-east-2.aws.neon.tech/linkseadb?sslmode=require
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: EMAIL_USER
        value: dimenzuri@gmail.com
      - key: EMAIL_PASSWORD
        value: hqbcxtstwpezdaea 